import Foundation

// Formal names checked 8 October 2026. Sources, rules and every judgement call: FORMAL_NAMES_SOURCES.md.
// - UN member states and observer states (Holy See, State of Palestine): the English "formal" names in UNTERM,
//   the United Nations Terminology Database (https://unterm.un.org/unterm2/en/country, country-name export),
//   cross-checked with the UN Protocol and Liaison Service's list of Heads of State, Heads of Government and
//   Ministers for Foreign Affairs (19 September 2026) and Wikipedia's "List of sovereign states". The Gambia keeps
//   the capital "The" used by that Protocol list and by its government.
// - Taiwan, Kosovo, Hong Kong, Macao and territories: their own constitutions, founding laws and government
//   websites: Taiwan's Office of the President and Ministry of Foreign Affairs, the Constitution of the Republic of
//   Kosovo, the Hong Kong and Macao Basic Laws, the Constitution of Puerto Rico, the Covenant with the Northern
//   Mariana Islands, the Government of the U.S. Virgin Islands, Australia's Christmas Island, Cocos (Keeling)
//   Islands, Norfolk Island and Heard Island and McDonald Islands Acts, the States of Guernsey, the Government of
//   Jersey, the Pitcairn Constitution Order 2010, and French law 55-1052 on the Terres australes et antarctiques
//   françaises.
// A leading "the" is dropped; official capitalisation and diacritics are kept.

extension CountryCatalog {
    /// Formal names for the World's places, keyed by ISO 3166-1 alpha-2 code, shown beneath the
    /// short name. UN member and observer states use the United Nations' formal names; other places
    /// use the official names their own governments use. Places whose formal name is the same as
    /// their short name are left out.
    static let formalNames: [String: String] = [
        "AD": "Principality of Andorra",
        "AF": "Islamic Republic of Afghanistan",
        "AL": "Republic of Albania",
        "AM": "Republic of Armenia",
        "AO": "Republic of Angola",
        "AR": "Argentine Republic",
        "AT": "Republic of Austria",
        "AZ": "Republic of Azerbaijan",
        "BD": "People's Republic of Bangladesh",
        "BE": "Kingdom of Belgium",
        "BG": "Republic of Bulgaria",
        "BH": "Kingdom of Bahrain",
        "BI": "Republic of Burundi",
        "BJ": "Republic of Benin",
        "BO": "Plurinational State of Bolivia",
        "BR": "Federative Republic of Brazil",
        "BS": "Commonwealth of The Bahamas",
        "BT": "Kingdom of Bhutan",
        "BW": "Republic of Botswana",
        "BY": "Republic of Belarus",
        "CC": "Territory of Cocos (Keeling) Islands",
        "CH": "Swiss Confederation",
        "CI": "Republic of Côte d'Ivoire",
        "CL": "Republic of Chile",
        "CM": "Republic of Cameroon",
        "CN": "People's Republic of China",
        "CO": "Republic of Colombia",
        "CR": "Republic of Costa Rica",
        "CU": "Republic of Cuba",
        "CV": "Republic of Cabo Verde",
        "CX": "Territory of Christmas Island",
        "CY": "Republic of Cyprus",
        "CZ": "Czech Republic",
        "DE": "Federal Republic of Germany",
        "DJ": "Republic of Djibouti",
        "DK": "Kingdom of Denmark",
        "DM": "Commonwealth of Dominica",
        "DZ": "People's Democratic Republic of Algeria",
        "EC": "Republic of Ecuador",
        "EE": "Republic of Estonia",
        "EG": "Arab Republic of Egypt",
        "ER": "State of Eritrea",
        "ES": "Kingdom of Spain",
        "ET": "Federal Democratic Republic of Ethiopia",
        "FI": "Republic of Finland",
        "FJ": "Republic of Fiji",
        "FR": "French Republic",
        "GA": "Gabonese Republic",
        "GB": "United Kingdom of Great Britain and Northern Ireland",
        "GG": "Bailiwick of Guernsey",
        "GH": "Republic of Ghana",
        "GM": "Republic of The Gambia",
        "GN": "Republic of Guinea",
        "GQ": "Republic of Equatorial Guinea",
        "GR": "Hellenic Republic",
        "GT": "Republic of Guatemala",
        "GW": "Republic of Guinea-Bissau",
        "GY": "Co-operative Republic of Guyana",
        "HK": "Hong Kong Special Administrative Region of the People's Republic of China",
        "HM": "Territory of Heard Island and McDonald Islands",
        "HN": "Republic of Honduras",
        "HR": "Republic of Croatia",
        "HT": "Republic of Haiti",
        "ID": "Republic of Indonesia",
        "IL": "State of Israel",
        "IN": "Republic of India",
        "IQ": "Republic of Iraq",
        "IR": "Islamic Republic of Iran",
        "IT": "Republic of Italy",
        "JE": "Bailiwick of Jersey",
        "JO": "Hashemite Kingdom of Jordan",
        "KE": "Republic of Kenya",
        "KG": "Kyrgyz Republic",
        "KH": "Kingdom of Cambodia",
        "KI": "Republic of Kiribati",
        "KM": "Union of the Comoros",
        "KP": "Democratic People's Republic of Korea",
        "KR": "Republic of Korea",
        "KW": "State of Kuwait",
        "KZ": "Republic of Kazakhstan",
        "LA": "Lao People's Democratic Republic",
        "LB": "Lebanese Republic",
        "LI": "Principality of Liechtenstein",
        "LK": "Democratic Socialist Republic of Sri Lanka",
        "LR": "Republic of Liberia",
        "LS": "Kingdom of Lesotho",
        "LT": "Republic of Lithuania",
        "LU": "Grand Duchy of Luxembourg",
        "LV": "Republic of Latvia",
        "LY": "State of Libya",
        "MA": "Kingdom of Morocco",
        "MC": "Principality of Monaco",
        "MD": "Republic of Moldova",
        "MG": "Republic of Madagascar",
        "MH": "Republic of the Marshall Islands",
        "MK": "Republic of North Macedonia",
        "ML": "Republic of Mali",
        "MM": "Republic of the Union of Myanmar",
        "MO": "Macao Special Administrative Region of the People's Republic of China",
        "MP": "Commonwealth of the Northern Mariana Islands",
        "MR": "Islamic Republic of Mauritania",
        "MT": "Republic of Malta",
        "MU": "Republic of Mauritius",
        "MV": "Republic of Maldives",
        "MW": "Republic of Malawi",
        "MX": "United Mexican States",
        "MZ": "Republic of Mozambique",
        "NA": "Republic of Namibia",
        "NE": "Republic of the Niger",
        "NF": "Territory of Norfolk Island",
        "NG": "Federal Republic of Nigeria",
        "NI": "Republic of Nicaragua",
        "NL": "Kingdom of the Netherlands",
        "NO": "Kingdom of Norway",
        "NR": "Republic of Naoero",
        "OM": "Sultanate of Oman",
        "PA": "Republic of Panama",
        "PE": "Republic of Peru",
        "PG": "Independent State of Papua New Guinea",
        "PH": "Republic of the Philippines",
        "PK": "Islamic Republic of Pakistan",
        "PL": "Republic of Poland",
        "PN": "Pitcairn, Henderson, Ducie and Oeno Islands",
        "PR": "Commonwealth of Puerto Rico",
        "PS": "State of Palestine",
        "PT": "Portuguese Republic",
        "PW": "Republic of Palau",
        "PY": "Republic of Paraguay",
        "QA": "State of Qatar",
        "RS": "Republic of Serbia",
        "RU": "Russian Federation",
        "RW": "Republic of Rwanda",
        "SA": "Kingdom of Saudi Arabia",
        "SC": "Republic of Seychelles",
        "SD": "Republic of the Sudan",
        "SE": "Kingdom of Sweden",
        "SG": "Republic of Singapore",
        "SI": "Republic of Slovenia",
        "SK": "Slovak Republic",
        "SL": "Republic of Sierra Leone",
        "SM": "Republic of San Marino",
        "SN": "Republic of Senegal",
        "SO": "Federal Republic of Somalia",
        "SR": "Republic of Suriname",
        "SS": "Republic of South Sudan",
        "ST": "Democratic Republic of Sao Tome and Principe",
        "SV": "Republic of El Salvador",
        "SY": "Syrian Arab Republic",
        "SZ": "Kingdom of Eswatini",
        "TD": "Republic of Chad",
        "TF": "French Southern and Antarctic Lands",
        "TG": "Togolese Republic",
        "TH": "Kingdom of Thailand",
        "TJ": "Republic of Tajikistan",
        "TL": "Democratic Republic of Timor-Leste",
        "TN": "Republic of Tunisia",
        "TO": "Kingdom of Tonga",
        "TR": "Republic of Türkiye",
        "TT": "Republic of Trinidad and Tobago",
        "TW": "Republic of China (Taiwan)",
        "TZ": "United Republic of Tanzania",
        "UG": "Republic of Uganda",
        "UY": "Oriental Republic of Uruguay",
        "UZ": "Republic of Uzbekistan",
        "VA": "Holy See",
        "VE": "Bolivarian Republic of Venezuela",
        "VI": "United States Virgin Islands",
        "VN": "Socialist Republic of Viet Nam",
        "VU": "Republic of Vanuatu",
        "WS": "Independent State of Samoa",
        "XC": "Turkish Republic of Northern Cyprus",
        "XK": "Republic of Kosovo",
        "YE": "Republic of Yemen",
        "ZA": "Republic of South Africa",
        "ZM": "Republic of Zambia",
        "ZW": "Republic of Zimbabwe",
    ]
}
